### ISSUE TITLE
Handling Types

### ISSUE THREAD

**Issue by bheemaguli** [NicolasCARPi/dropzone#7]
I would like to know if there is support for types for this fork.

Importing 
```javascript
import { Dropzone } from "@deltablot/dropzone";
````

will raise error
```javascript
Could not find a declaration file for module '@deltablot/dropzone'. '.../@deltablot+dropzone@7.1.2/node_modules/@deltablot/dropzone/dist/dropzone.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/deltablot__dropzone` if it exists or add a new declaration (.d.ts) file containing `declare module '@deltablot/dropzone';`ts(7016)
````
and will make the build with typsecript fail.

If there is no much deviation, is there a way to declare `@types/dropzone` as types for this package?

**Comment by NicolasCARPi** [comment]
Hello @bheemaguli,

I've pushed a commit that adds types directly in this project. Could you please try the `master` branch and let me know if all is good? Then I'll make a new release.

**Comment by bheemaguli** [comment]
Tried to build and the export doesn't seem to have all the types like DropzoneOptions, DropzoneDictFileSizeUnits and son on. It seems ts is building only the parent exports.

**Comment by NicolasCARPi** [comment]
It seems `dropzone.d.ts` file contains `Emitter`, but not `options`, I don't know why. The `options` types are correctly generated (`dist/options.d.ts`), but not integrated in the main file. :man_shrugging:

**Comment by bheemaguli** [comment]
Will try to look into this in this weekend.

**Comment by NicolasCARPi** [comment]
@bheemaguli did you find out anything about this issue?

**Comment by bheemaguli** [comment]
I have not much experience in this, but from what I can see, you should either have to convert the project to typescript or modify https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types%2Fdropzone%2Fv4%2Fdropzone-tests.ts to handle the recent changes and merge this fork as a separate package to DefinitelyTyped repo so that the package is installable as a dependency.

**Comment by doberkofler** [comment]
@NicolasCARPi Thank you for all you work!

I'm curretly unable to switch to this fork as there is no "proper" type information available.

The original dropzone repository did not contain it's own type definitions but The definition in DefinitelyTyped `@types/dropzone` was very good.

I see no need to rewrite the code in TypeScript, because the source is not written in TypeScript, the "generated" type definition is very generic and except for the "names" almost everything actually untyped by using the `any` type. The existing type definitions allow to import the package but offer no proper type checking at all.

I would suggest to maintain the type definition locally but instead of generating  them from JavaScript to craft them based on the original definition in `@types/dropzone` version `5.7.8`.
I'm not sure what all changed since version `5.7.8` but based on the changelog the api seems to have been quite stable and the changed should (I know) be limited.

Maintaining the types as part of this fork is the preferred option as it does not require to install the type definition separately but alternatively you could also remove the generated type definitions and create a new external DefinitelyTyped definition `@types/deltablot__dropzone` again based on the original definition in `@types/dropzone` version `5.7.8`.

**Comment by doberkofler** [comment]
@NicolasCARPi 

I prepared the following type definition file that I'm currently using to patch (patch-package) the existing type definition.
You might want to stop generating the type definition and test with this file.

[dropzone.d.ts.zip](https://github.com/user-attachments/files/17519176/dropzone.d.ts.zip)

**Comment by NicolasCARPi** [comment]
But then it won't be automatic and will require more work to maintain, no? IMHO the types definition file **must** be automatically generated. And eventually this project should be re-written with typescript, because working with plain javascript is a PITA. In fact, I did start the re-write already on a branch. But as you can imagine, this is not a high priority. As you said, the public api doesn't change much, so maybe using your file and calling it a day would be better than generating automatically an incomplete file... Want to make a PR?

**Comment by doberkofler** [comment]
> But then it won't be automatic and will require more work to maintain, no?
yes, but as long as the api does not change no changes are needed

>IMHO the types definition file **must** be automatically generated.
yes, but the definitions generated from JavaScript are almost useless

>And eventually this project should be re-written with typescript, because working with plain javascript is a PITA. In fact, I did start the re-write already on a branch. But as you can imagine, this is not a high priority.
I personally would not survive a day without TypeScript but a rewrite will take some time, I guess

>As you said, the public api doesn't change much, so maybe using your file and calling it a day would be better than generating automatically an incomplete file... Want to make a PR?
I can try

**Comment by doberkofler** [comment]
I just pushed #19
